# Local PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/food-ordering
spring.datasource.username=postgres
spring.datasource.password=1789
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jwt
jwt.secret=your-256-bit-secret-at-least-32-chars-long-here
jwt.expiration=86400000