# Local PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/food-ordering
spring.datasource.username=postgres
spring.datasource.password=1789
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Port
server.port=9090

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Jwt
jwt.secret=food-ordering-super-secret-key-minimum-32-chars-ok
jwt.expiration=86400000